// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package kprpb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Descriptor
	PackageManifest
	ListRequest
	ListResponse
	ListTagsRequest
	ListTagsResponse
	TagRequest
	BlobRequest
	BlobResponse
*/
package kprpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Descriptor struct {
	MediaType string `protobuf:"bytes,1,opt,name=mediaType" json:"mediaType,omitempty"`
	Size      int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Digest    string `protobuf:"bytes,3,opt,name=digest" json:"digest,omitempty"`
}

func (m *Descriptor) Reset()                    { *m = Descriptor{} }
func (m *Descriptor) String() string            { return proto.CompactTextString(m) }
func (*Descriptor) ProtoMessage()               {}
func (*Descriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PackageManifest struct {
	SchemaVersion int64         `protobuf:"varint,1,opt,name=schemaVersion" json:"schemaVersion,omitempty"`
	MediaType     string        `protobuf:"bytes,2,opt,name=mediaType" json:"mediaType,omitempty"`
	Package       *Descriptor   `protobuf:"bytes,3,opt,name=package" json:"package,omitempty"`
	Dependencies  []*Descriptor `protobuf:"bytes,4,rep,name=dependencies" json:"dependencies,omitempty"`
	Packages      []*Descriptor `protobuf:"bytes,5,rep,name=packages" json:"packages,omitempty"`
}

func (m *PackageManifest) Reset()                    { *m = PackageManifest{} }
func (m *PackageManifest) String() string            { return proto.CompactTextString(m) }
func (*PackageManifest) ProtoMessage()               {}
func (*PackageManifest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PackageManifest) GetPackage() *Descriptor {
	if m != nil {
		return m.Package
	}
	return nil
}

func (m *PackageManifest) GetDependencies() []*Descriptor {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *PackageManifest) GetPackages() []*Descriptor {
	if m != nil {
		return m.Packages
	}
	return nil
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListResponse struct {
	Repos []*ListResponse_Repos `protobuf:"bytes,1,rep,name=repos" json:"repos,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListResponse) GetRepos() []*ListResponse_Repos {
	if m != nil {
		return m.Repos
	}
	return nil
}

type ListResponse_Repos struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListResponse_Repos) Reset()                    { *m = ListResponse_Repos{} }
func (m *ListResponse_Repos) String() string            { return proto.CompactTextString(m) }
func (*ListResponse_Repos) ProtoMessage()               {}
func (*ListResponse_Repos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ListTagsRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListTagsRequest) Reset()                    { *m = ListTagsRequest{} }
func (m *ListTagsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTagsRequest) ProtoMessage()               {}
func (*ListTagsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListTagsResponse struct {
	Name string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tags []*ListTagsResponse_Tags `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
}

func (m *ListTagsResponse) Reset()                    { *m = ListTagsResponse{} }
func (m *ListTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTagsResponse) ProtoMessage()               {}
func (*ListTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListTagsResponse) GetTags() []*ListTagsResponse_Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListTagsResponse_Tags struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListTagsResponse_Tags) Reset()                    { *m = ListTagsResponse_Tags{} }
func (m *ListTagsResponse_Tags) String() string            { return proto.CompactTextString(m) }
func (*ListTagsResponse_Tags) ProtoMessage()               {}
func (*ListTagsResponse_Tags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type TagRequest struct {
	Name string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tag  string      `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	Desc *Descriptor `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *TagRequest) Reset()                    { *m = TagRequest{} }
func (m *TagRequest) String() string            { return proto.CompactTextString(m) }
func (*TagRequest) ProtoMessage()               {}
func (*TagRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TagRequest) GetDesc() *Descriptor {
	if m != nil {
		return m.Desc
	}
	return nil
}

type BlobRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Digest string `protobuf:"bytes,2,opt,name=digest" json:"digest,omitempty"`
	Blob   []byte `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (m *BlobRequest) Reset()                    { *m = BlobRequest{} }
func (m *BlobRequest) String() string            { return proto.CompactTextString(m) }
func (*BlobRequest) ProtoMessage()               {}
func (*BlobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type BlobResponse struct {
	Blob []byte `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (m *BlobResponse) Reset()                    { *m = BlobResponse{} }
func (m *BlobResponse) String() string            { return proto.CompactTextString(m) }
func (*BlobResponse) ProtoMessage()               {}
func (*BlobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*Descriptor)(nil), "kprpb.Descriptor")
	proto.RegisterType((*PackageManifest)(nil), "kprpb.PackageManifest")
	proto.RegisterType((*ListRequest)(nil), "kprpb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "kprpb.ListResponse")
	proto.RegisterType((*ListResponse_Repos)(nil), "kprpb.ListResponse.Repos")
	proto.RegisterType((*ListTagsRequest)(nil), "kprpb.ListTagsRequest")
	proto.RegisterType((*ListTagsResponse)(nil), "kprpb.ListTagsResponse")
	proto.RegisterType((*ListTagsResponse_Tags)(nil), "kprpb.ListTagsResponse.Tags")
	proto.RegisterType((*TagRequest)(nil), "kprpb.TagRequest")
	proto.RegisterType((*BlobRequest)(nil), "kprpb.BlobRequest")
	proto.RegisterType((*BlobResponse)(nil), "kprpb.BlobResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Repo service

type RepoClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	GetTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*PackageManifest, error)
	PutTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*Descriptor, error)
	DeleteTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*Descriptor, error)
}

type repoClient struct {
	cc *grpc.ClientConn
}

func NewRepoClient(cc *grpc.ClientConn) RepoClient {
	return &repoClient{cc}
}

func (c *repoClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/kprpb.Repo/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	out := new(ListTagsResponse)
	err := grpc.Invoke(ctx, "/kprpb.Repo/ListTags", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoClient) GetTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*PackageManifest, error) {
	out := new(PackageManifest)
	err := grpc.Invoke(ctx, "/kprpb.Repo/GetTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoClient) PutTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*Descriptor, error) {
	out := new(Descriptor)
	err := grpc.Invoke(ctx, "/kprpb.Repo/PutTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoClient) DeleteTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*Descriptor, error) {
	out := new(Descriptor)
	err := grpc.Invoke(ctx, "/kprpb.Repo/DeleteTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Repo service

type RepoServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	GetTag(context.Context, *TagRequest) (*PackageManifest, error)
	PutTag(context.Context, *TagRequest) (*Descriptor, error)
	DeleteTag(context.Context, *TagRequest) (*Descriptor, error)
}

func RegisterRepoServer(s *grpc.Server, srv RepoServer) {
	s.RegisterService(&_Repo_serviceDesc, srv)
}

func _Repo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Repo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repo_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Repo/ListTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repo_GetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).GetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Repo/GetTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).GetTag(ctx, req.(*TagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repo_PutTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).PutTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Repo/PutTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).PutTag(ctx, req.(*TagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repo_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Repo/DeleteTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).DeleteTag(ctx, req.(*TagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Repo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kprpb.Repo",
	HandlerType: (*RepoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Repo_List_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Repo_ListTags_Handler,
		},
		{
			MethodName: "GetTag",
			Handler:    _Repo_GetTag_Handler,
		},
		{
			MethodName: "PutTag",
			Handler:    _Repo_PutTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Repo_DeleteTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for Blob service

type BlobClient interface {
	PutBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*Descriptor, error)
	// TODO: custom marshaller
	GetBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*BlobResponse, error)
}

type blobClient struct {
	cc *grpc.ClientConn
}

func NewBlobClient(cc *grpc.ClientConn) BlobClient {
	return &blobClient{cc}
}

func (c *blobClient) PutBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*Descriptor, error) {
	out := new(Descriptor)
	err := grpc.Invoke(ctx, "/kprpb.Blob/PutBlob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobClient) GetBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*BlobResponse, error) {
	out := new(BlobResponse)
	err := grpc.Invoke(ctx, "/kprpb.Blob/GetBlob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blob service

type BlobServer interface {
	PutBlob(context.Context, *BlobRequest) (*Descriptor, error)
	// TODO: custom marshaller
	GetBlob(context.Context, *BlobRequest) (*BlobResponse, error)
}

func RegisterBlobServer(s *grpc.Server, srv BlobServer) {
	s.RegisterService(&_Blob_serviceDesc, srv)
}

func _Blob_PutBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServer).PutBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Blob/PutBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServer).PutBlob(ctx, req.(*BlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blob_GetBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServer).GetBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Blob/GetBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServer).GetBlob(ctx, req.(*BlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blob_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kprpb.Blob",
	HandlerType: (*BlobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutBlob",
			Handler:    _Blob_PutBlob_Handler,
		},
		{
			MethodName: "GetBlob",
			Handler:    _Blob_GetBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x94, 0xd1, 0x4e, 0xd4, 0x5c,
	0x10, 0xc7, 0xd3, 0xdd, 0xee, 0x02, 0xc3, 0xf2, 0xc1, 0x37, 0x28, 0xd4, 0x02, 0x09, 0x29, 0x62,
	0x10, 0x63, 0x6b, 0x56, 0xf1, 0x82, 0xc4, 0x1b, 0x83, 0xe1, 0x46, 0x12, 0xd2, 0x10, 0x22, 0xc6,
	0x9b, 0xb3, 0xbb, 0x43, 0x69, 0x58, 0x7a, 0x6a, 0xcf, 0xc1, 0xa8, 0x84, 0x1b, 0x5f, 0xc1, 0x77,
	0xf1, 0x41, 0xf4, 0x15, 0xbc, 0xf0, 0x31, 0xcc, 0x99, 0x76, 0xed, 0x2e, 0x74, 0x37, 0xdc, 0x9d,
	0x39, 0xfb, 0x9f, 0xdf, 0xcc, 0x99, 0xff, 0x6c, 0x61, 0x4e, 0x51, 0xf6, 0x29, 0xee, 0x92, 0x9f,
	0x66, 0x52, 0x4b, 0x6c, 0x9c, 0xa7, 0x59, 0xda, 0x71, 0x57, 0x23, 0x29, 0xa3, 0x3e, 0x05, 0x22,
	0x8d, 0x03, 0x91, 0x24, 0x52, 0x0b, 0x1d, 0xcb, 0x44, 0xe5, 0x22, 0xef, 0x18, 0x60, 0x8f, 0x54,
	0x37, 0x8b, 0x53, 0x2d, 0x33, 0x5c, 0x85, 0x99, 0x0b, 0xea, 0xc5, 0xe2, 0xe8, 0x4b, 0x4a, 0x8e,
	0xb5, 0x6e, 0x6d, 0xcd, 0x84, 0xe5, 0x05, 0x22, 0xd8, 0x2a, 0xfe, 0x4a, 0x4e, 0x6d, 0xdd, 0xda,
	0xaa, 0x87, 0x7c, 0xc6, 0x25, 0x68, 0xf6, 0xe2, 0x88, 0x94, 0x76, 0xea, 0x2c, 0x2f, 0x22, 0xef,
	0x8f, 0x05, 0xf3, 0x87, 0xa2, 0x7b, 0x2e, 0x22, 0x3a, 0x10, 0x49, 0x7c, 0x4a, 0x4a, 0xe3, 0x43,
	0x98, 0x53, 0xdd, 0x33, 0xba, 0x10, 0xc7, 0x94, 0xa9, 0x58, 0x26, 0x5c, 0xa1, 0x1e, 0x8e, 0x5e,
	0x8e, 0xf6, 0x50, 0xbb, 0xd9, 0xc3, 0x13, 0x98, 0x4a, 0x73, 0x2c, 0x17, 0x9c, 0x6d, 0xff, 0xef,
	0xf3, 0x33, 0xfd, 0xf2, 0x15, 0xe1, 0x40, 0x81, 0x3b, 0xd0, 0xea, 0x51, 0x4a, 0x49, 0x8f, 0x92,
	0x6e, 0x4c, 0xca, 0xb1, 0xd7, 0xeb, 0xd5, 0x19, 0x23, 0x32, 0x7c, 0x0a, 0xd3, 0x05, 0x41, 0x39,
	0x8d, 0x71, 0x29, 0xff, 0x24, 0xde, 0x1c, 0xcc, 0xbe, 0x8d, 0x95, 0x0e, 0xe9, 0xe3, 0xa5, 0x79,
	0xf9, 0x07, 0x68, 0xe5, 0xa1, 0x4a, 0x65, 0xa2, 0x08, 0x03, 0x68, 0x64, 0x94, 0x4a, 0xe5, 0x58,
	0x8c, 0x7a, 0x50, 0xa0, 0x86, 0x35, 0x7e, 0x68, 0x04, 0x61, 0xae, 0x73, 0x57, 0xa0, 0xc1, 0xb1,
	0x99, 0x77, 0x22, 0x2e, 0x06, 0x46, 0xf0, 0xd9, 0xdb, 0x84, 0x79, 0x93, 0x79, 0x24, 0x22, 0x55,
	0x14, 0xac, 0x94, 0x69, 0x58, 0x28, 0x65, 0x45, 0x23, 0x15, 0x3a, 0x7c, 0x06, 0xb6, 0x16, 0x91,
	0x72, 0x6a, 0xdc, 0xdb, 0xea, 0x50, 0x6f, 0xc3, 0xa9, 0x3e, 0x07, 0xac, 0x74, 0x5d, 0xb0, 0x4d,
	0x54, 0x59, 0xf5, 0x04, 0xe0, 0x48, 0x44, 0x13, 0xfa, 0xc2, 0x05, 0xa8, 0x6b, 0x11, 0x15, 0xb6,
	0x9a, 0x23, 0x6e, 0x82, 0xdd, 0x23, 0xd5, 0x1d, 0xef, 0x26, 0xff, 0xec, 0x1d, 0xc0, 0xec, 0xeb,
	0xbe, 0xec, 0x4c, 0x62, 0x97, 0xab, 0x58, 0x1b, 0x5e, 0x45, 0xa3, 0xed, 0xf4, 0x65, 0x87, 0x2b,
	0xb4, 0x42, 0x3e, 0x7b, 0x1e, 0xb4, 0x72, 0x5c, 0x39, 0x1b, 0xd6, 0x58, 0xa5, 0xa6, 0xfd, 0xa3,
	0x0e, 0xb6, 0x31, 0x02, 0xdf, 0x80, 0x6d, 0x26, 0x82, 0x38, 0x62, 0x1d, 0x37, 0xe2, 0x2e, 0x56,
	0xd8, 0xe9, 0xdd, 0xfb, 0xf6, 0xeb, 0xf7, 0xf7, 0xda, 0x7f, 0xd8, 0x0a, 0xd8, 0xd1, 0x20, 0x4e,
	0x7a, 0xf4, 0x19, 0xdf, 0xc3, 0xf4, 0x60, 0xb0, 0xb8, 0x74, 0x6b, 0xd2, 0x39, 0x6e, 0x79, 0x8c,
	0x03, 0xde, 0x1a, 0x23, 0x97, 0xf1, 0x7e, 0x81, 0xbc, 0x32, 0x4f, 0x7e, 0xb5, 0xbd, 0x7d, 0x1d,
	0x18, 0x57, 0xf0, 0x1d, 0x34, 0xf7, 0xc9, 0x64, 0xe0, 0x60, 0x82, 0xa5, 0x11, 0xee, 0xa0, 0xd8,
	0x8d, 0xff, 0xa3, 0xb7, 0xc1, 0xcc, 0x35, 0x5c, 0xa9, 0x64, 0x06, 0x57, 0x5a, 0x44, 0xd7, 0x78,
	0x02, 0xcd, 0xc3, 0xcb, 0x71, 0xe4, 0xdb, 0x76, 0x79, 0x8f, 0x19, 0xba, 0xe1, 0x4e, 0x82, 0xee,
	0xb2, 0xa7, 0x78, 0x0c, 0x33, 0x7b, 0xd4, 0x27, 0x4d, 0x77, 0xa7, 0x17, 0x2d, 0x4f, 0xa4, 0xb7,
	0x7f, 0x5a, 0x60, 0x1b, 0x77, 0xf1, 0x14, 0xa6, 0x0e, 0x2f, 0x35, 0x1f, 0x07, 0xde, 0x0d, 0x2d,
	0x51, 0x15, 0xff, 0x05, 0xf3, 0x7d, 0xf7, 0xd1, 0x2d, 0xbe, 0x59, 0x09, 0x15, 0xa8, 0x33, 0xd1,
	0xde, 0x79, 0x19, 0x5c, 0xe5, 0xab, 0x75, 0xbd, 0xcb, 0x9b, 0x82, 0x1d, 0x98, 0xda, 0xa7, 0xf1,
	0x75, 0x16, 0x47, 0xee, 0x0a, 0x43, 0x7d, 0xae, 0xb4, 0x85, 0x77, 0xac, 0xd4, 0x69, 0xf2, 0xf7,
	0xfa, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x87, 0x59, 0x71, 0xe5, 0x05, 0x00, 0x00,
}
