// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package kprpb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	ListRequest
	ListResponse
	ListTagsRequest
	ListTagsResponse
*/
package kprpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListResponse struct {
	Repos []*ListResponse_Repos `protobuf:"bytes,1,rep,name=repos" json:"repos,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListResponse) GetRepos() []*ListResponse_Repos {
	if m != nil {
		return m.Repos
	}
	return nil
}

type ListResponse_Repos struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListResponse_Repos) Reset()                    { *m = ListResponse_Repos{} }
func (m *ListResponse_Repos) String() string            { return proto.CompactTextString(m) }
func (*ListResponse_Repos) ProtoMessage()               {}
func (*ListResponse_Repos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type ListTagsRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListTagsRequest) Reset()                    { *m = ListTagsRequest{} }
func (m *ListTagsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTagsRequest) ProtoMessage()               {}
func (*ListTagsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListTagsResponse struct {
	Name string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tags []*ListTagsResponse_Tags `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
}

func (m *ListTagsResponse) Reset()                    { *m = ListTagsResponse{} }
func (m *ListTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTagsResponse) ProtoMessage()               {}
func (*ListTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListTagsResponse) GetTags() []*ListTagsResponse_Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListTagsResponse_Tags struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListTagsResponse_Tags) Reset()                    { *m = ListTagsResponse_Tags{} }
func (m *ListTagsResponse_Tags) String() string            { return proto.CompactTextString(m) }
func (*ListTagsResponse_Tags) ProtoMessage()               {}
func (*ListTagsResponse_Tags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func init() {
	proto.RegisterType((*ListRequest)(nil), "kprpb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "kprpb.ListResponse")
	proto.RegisterType((*ListResponse_Repos)(nil), "kprpb.ListResponse.Repos")
	proto.RegisterType((*ListTagsRequest)(nil), "kprpb.ListTagsRequest")
	proto.RegisterType((*ListTagsResponse)(nil), "kprpb.ListTagsResponse")
	proto.RegisterType((*ListTagsResponse_Tags)(nil), "kprpb.ListTagsResponse.Tags")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Repo service

type RepoClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
}

type repoClient struct {
	cc *grpc.ClientConn
}

func NewRepoClient(cc *grpc.ClientConn) RepoClient {
	return &repoClient{cc}
}

func (c *repoClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/kprpb.Repo/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	out := new(ListTagsResponse)
	err := grpc.Invoke(ctx, "/kprpb.Repo/ListTags", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Repo service

type RepoServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
}

func RegisterRepoServer(s *grpc.Server, srv RepoServer) {
	s.RegisterService(&_Repo_serviceDesc, srv)
}

func _Repo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Repo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repo_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kprpb.Repo/ListTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Repo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kprpb.Repo",
	HandlerType: (*RepoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Repo_List_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Repo_ListTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x49, 0x4d, 0x4a, 0x7d, 0xb5, 0x2a, 0x4f, 0xb4, 0x71, 0xac, 0x50, 0x06, 0x84, 0xd2,
	0xc5, 0x8c, 0xd4, 0xb5, 0x78, 0x01, 0x57, 0xc1, 0x95, 0xb8, 0x99, 0xca, 0x10, 0x82, 0x3a, 0x33,
	0x66, 0x46, 0x37, 0xe2, 0xc6, 0x2b, 0x78, 0x04, 0x8f, 0xe4, 0x15, 0x3c, 0x88, 0xcc, 0x4b, 0xc5,
	0x88, 0xe9, 0x2e, 0x3f, 0x7c, 0xef, 0xcf, 0xf7, 0xde, 0xc0, 0xc8, 0xeb, 0xfa, 0xb9, 0xba, 0xd5,
	0xc2, 0xd5, 0x36, 0x58, 0xcc, 0xee, 0x5c, 0xed, 0x96, 0x6c, 0x52, 0x5a, 0x5b, 0xde, 0x6b, 0xa9,
	0x5c, 0x25, 0x95, 0x31, 0x36, 0xa8, 0x50, 0x59, 0xe3, 0x1b, 0x88, 0x8f, 0x60, 0x78, 0x59, 0xf9,
	0x50, 0xe8, 0xc7, 0x27, 0xed, 0x03, 0xbf, 0x81, 0xad, 0x26, 0x7a, 0x67, 0x8d, 0xd7, 0x28, 0x21,
	0xab, 0xb5, 0xb3, 0x3e, 0x4f, 0xa6, 0x1b, 0xb3, 0xe1, 0xe2, 0x50, 0x50, 0xa7, 0x68, 0x33, 0xa2,
	0x88, 0x40, 0xd1, 0x70, 0xec, 0x08, 0x32, 0xca, 0x88, 0x90, 0x1a, 0xf5, 0xa0, 0xf3, 0x64, 0x9a,
	0xcc, 0x36, 0x0b, 0xfa, 0xe6, 0x27, 0xb0, 0x13, 0x27, 0xaf, 0x54, 0xe9, 0x57, 0x3f, 0xec, 0xc4,
	0x02, 0xec, 0xfe, 0x62, 0x2b, 0x91, 0x0e, 0x0e, 0x4f, 0x21, 0x0d, 0xaa, 0xf4, 0x79, 0x8f, 0xdc,
	0x26, 0x2d, 0xb7, 0xf6, 0xa8, 0xa0, 0x40, 0x24, 0x63, 0x90, 0xc6, 0xd4, 0xd5, 0xb6, 0xf8, 0x48,
	0x20, 0x8d, 0xea, 0x78, 0x01, 0x69, 0xec, 0x40, 0xfc, 0xb3, 0x2c, 0xe9, 0xb2, 0xbd, 0x8e, 0x03,
	0xf0, 0xed, 0xb7, 0xcf, 0xaf, 0xf7, 0xde, 0x00, 0xfb, 0x92, 0x6e, 0x80, 0xd7, 0x30, 0xf8, 0x91,
	0xc0, 0x83, 0x7f, 0x56, 0x4d, 0xd1, 0x78, 0x8d, 0x2d, 0x3f, 0xa6, 0xb2, 0x31, 0xee, 0xcb, 0x97,
	0xa8, 0x75, 0x4e, 0x95, 0x72, 0x3e, 0x7f, 0x95, 0x71, 0x83, 0x65, 0x9f, 0x9e, 0xed, 0xec, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x98, 0xa7, 0x8f, 0x1a, 0xec, 0x01, 0x00, 0x00,
}
